# Generated by Django 2.1.4 on 2018-12-11 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250, unique=True, verbose_name='Judul Artikel')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('isi', models.TextField(blank=True)),
                ('gambar', models.ImageField(blank=True, upload_to='artikel/')),
                ('likes', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['modified_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250, unique=True, verbose_name='Judul Kategori')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Kategori')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='penulis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['judul'], name='judul_index'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['penulis'], name='penulis_index'),
        ),
    ]
