# Generated by Django 2.1.4 on 2019-01-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181211_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['judul'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
